# Generated by Django 3.1.3 on 2020-11-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A_Database_Model_ORM_Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.CharField(default='', max_length=30)),
                ('test2', models.CharField(default='', max_length=30)),
                ('test3', models.CharField(default='', max_length=30)),
                ('test4', models.CharField(default='', max_length=30)),
                ('test5', models.CharField(default='', max_length=30)),
                ('test6', models.CharField(default='', max_length=30)),
                ('test7', models.CharField(default='', max_length=30)),
                ('test8', models.CharField(default='', max_length=30)),
                ('test9', models.CharField(default='', max_length=30)),
                ('test10', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
