"""
Django settings for Django_Backend_Example project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
import django

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7fc7zf(r#0r8kmi@1=@8x80s3nm#zbdwb&_8j^2imv$*!le$_y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True #TODO Change This In Production Environment
Production = False #TODO Change This In Production Environment

if Production == False:
    HOST_SERVER_URL = 'http://localhost:8000/'
    SITE_URL = 'http://localhost:8000/'
    ALLOWED_HOSTS = [
        'localhost'
    ]

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'Django_Example_Database',
            'USER': 'test_user',
            'PASSWORD': 'PassMySQL#2020',
            'HOST': 'localhost',
            'PORT': '3306'
        }
    }
    CORS_ORIGIN_WHITELIST = (
        'http://localhost:4200',
        'http://0.0.0.0:4200',
        'http://192.168.43.14:4200', #TODO
        'http://localhost:4200',
    )
    #CORS_ORIGIN_REGEX_WHITELIST = [
    #    '**',
    #]
else:
    SECURE_SSL_REDIRECT = True
    HOST_SERVER_URL = 'https://serveruser.com:8000/' #TODO
    SITE_URL = 'https://serveruser.com:8000/' #TODO
    ALLOWED_HOSTS = [
        'serveruser.com',
        '10.112.12.12',
    ]

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'Django_Example_Database',
            'USER': 'test_user',
            'PASSWORD': 'PassMySQL#2020',
            'HOST': '1.2.3.4',
            'PORT': '3306'
        }
    }

    CORS_ORIGIN_WHITELIST = (
        'http://serveruser.com',
        'https://serveruser.com',
    )
    #CORS_ORIGIN_REGEX_WHITELIST = [
    #   '**'
    #]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'A',
    'B',
    'C'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Django_Backend_Example.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Django_Backend_Example.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases



# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
